### ISSUE TITLE
Double clicking the "Expand Feed" triangle duplicates the feed entries and then closes only one set

### ISSUE THREAD

**Issue by sarvagnan** [scripting/feedlandSupport#107]
https://user-images.githubusercontent.com/860916/197955054-07bb7214-02c3-47dc-9a52-fba6e4accdaf.mov

I have attached a screen recording showing this behaviour. I would be happy to provide more information if needed.

Thank you!

**Comment by scripting** [comment]
@sarvagnan -- first thanks for the report. I'm not able to reproduce it here. See attached video. 

https://user-images.githubusercontent.com/1686843/198054394-7bdf58cd-31ff-420f-a5d3-d7d8ef5a9dcb.mov

**Comment by scripting** [comment]
BTW, there will be *lots* of bugs like this. New software. :smile:

**Comment by sarvagnan** [comment]
Thank you! The comment about the site maybe not knowing that the site has been expanded due to connection speed was helpful as I think that is the issue. I have a fairly fast connection but I was able to trigger this in a different way. If I expand a feed entry with a single click, double clicking on the triangle works as designed i.e. it expands and hides the feed with each click. However, if I double click a feed without first expanding it, then it duplicates the entries. This leads me to believe that it is a loading issue.
https://user-images.githubusercontent.com/860916/198079864-f40708b6-3759-404e-aa1a-52a2e57727c0.mov

**Comment by scripting** [comment]
@sarvagnan -- I've made the change. It won't start another expansion operation if one is already pending. It's version 0.4.5, you can see the version number in the upper right corner of the screen. 

Please let me know if this fixed the problem. ;-)

**Comment by sarvagnan** [comment]
It has stopped now. Thank you!
