### ISSUE TITLE
Feed appears in wrong category

### ISSUE THREAD

**Issue by scotthansonde** [scripting/feedlandSupport#123]
I subscribe to the Memeorandum feed, and have it in the All and Memeo categories.

![CleanShot 2022-11-03 at 16 18 54](https://user-images.githubusercontent.com/8681117/199764028-61753bea-a1a1-4101-8792-a64b2c6d6e6c.png)

However, the feed also appears in my Me category.

![CleanShot 2022-11-03 at 16 19 29](https://user-images.githubusercontent.com/8681117/199764162-736c30be-fba6-4901-8bfa-25bbe45e02a3.png)

I have tried adding Memeorandum to Me, then removing it from Me, with no effect.

Here are my Category preferences. 
![CleanShot 2022-11-03 at 16 22 20](https://user-images.githubusercontent.com/8681117/199764469-a2857206-fa4f-4018-84d3-df91f6078f57.png)

**Comment by scripting** [comment]
@scotthansonde -- i believe this bug is now. please give it a try and let me know.

**Comment by scotthansonde** [comment]
@scripting I tried it out and it appears to be fixed. I no longer see ‘Memeo’ feeds in the ‘Me’ category.

**Comment by scripting** [comment]
@scotthansonde -- thanks for your help! as usual your bug reporting is top rate. :smile:
