### ISSUE TITLE
Request for feature, different tabs for sets of sources

### ISSUE THREAD

**Issue by faffa42** [scripting/feedlandSupport#124]
Is it possible to have different news tabs for selected feeds? Let's say, a news feed from a group I created out of all the tech stuff, another one from all the music feeds and so on. It would help me to scroll exactly the things I need in a specific moment. 
Using FeedLand mostly for work it would help to read a specific set of sources in the morning, another one when I'm not and I just want to be entairtained. Thx!

**Comment by scripting** [comment]
@faffa42 -- welcome! (to everyone else, Faffa was my host along with Anna Masera when I visited Torino a couple of years ago. They were amazing hosts. 

Anyway -- what you ask for is what FeedLand was built to do.

What you are looking for are Categories. 

http://docs.feedland.org/categories.opml
