### ISSUE TITLE
Strict date ordered posts?

### ISSUE THREAD

**Issue by pitosalas** [scripting/feedlandSupport#137]
Hi Dave, congratulations on your product and fast public progress on it. I always enjoy reading your blog. I was playing with feedland. I was looking for a strictly date ordered list of posts,  not grouped by feed? I would have thought that was something you had?

**Comment by scripting** [comment]
Hi @pitosalas -- nice to see you here. 

This is how it works.

When FeedLand is building a timeline, it asks for all the items that qualify (by subscriber, category, etc) in the order that they were added to the database. As you say "strictly date ordered."

As it builds the timeline, if item X+1 is from the same feed as item X it groups them, to not have to repeat the feed info. Same with X+2 and so on until it finds one that is not from the same feed. THen it closes out that group and starts another.

**Comment by pitosalas** [comment]
I see. Keep up the great work. 

Thanks. Ok to close.
