### ISSUE TITLE
Anil Dash feed readable in river but not mailbox

### ISSUE THREAD

**Issue by mistersugar** [scripting/feedlandSupport#159]
I wanted to read Anil Dash's blog in Feedland so I went to the feed info page http://feedland.org/?feedurl=https%3A%2F%2Fanildash.com%2Frss%2F. 

I selected View as river and as expected Anil's blog posts are readable in the river. I then selected View as mailbox, but the page is empty beneath the menu bar. There is an error in the console but that error has my email secret so I won't post it here. The error message concludes with "Failed to load resource: the server responded with a status of 500 (Internal Server Error)"

<img width="857" alt="Screenshot 2022-12-31 at 1 41 51 PM" src="https://user-images.githubusercontent.com/3846301/210152967-aa9ef4bf-4a87-4464-8f66-3ea97488db18.png">

I have tried multiple other feeds and I am able to view each in the river and mailbox.

I am using Feedland in Safari.

**Comment by scripting** [comment]
@mistersugar -- it doesn't appear to be a feedland issue. when i try to read his feed in a script outside of feedland it returns nothing. sometime other servers have problems, this might be one of those times. 

https://anildash.com/rss/

**Comment by mistersugar** [comment]
Thank you for checking.
