### ISSUE TITLE
Clicking through to title-less posts

### ISSUE THREAD

**Issue by josephzitt** [scripting/feedlandSupport#162]
In my news river, I see this item from a title-less feed:
![image](https://user-images.githubusercontent.com/29645517/210328604-c3471882-0c41-45b2-afc5-f04a623d63a6.png)
I don't see a way to click through to the item itself, as I would in clicking on the blue title of an item from a titled feed.

Going to the blog itself and scrolling to the item, I see that it does have further content (in the form of a graphic)  which is needed to see what the text is talking about:
![image](https://user-images.githubusercontent.com/29645517/210329043-c85dfa8b-6aa4-40cb-a44e-4dd905327ed1.png)

Is it possible to get directly to the item from the river?

**Comment by scripting** [comment]
Please click on the </> icon and copy the text and paste it in your reply, or provide the url of the feed. This is the same as any other issue, I can’t see what you’re seeing without the ability to reproduce.

**Comment by josephzitt** [comment]
Here's what the </> icon shows me:
In which @timbray makes an interesting argument, or rather, response:

    {
        "feedUrl": "https://arvr.social/@mpesce.rss",
        "guid": "https://arvr.social/@mpesce/109623178869848080",
        "link": "https://arvr.social/@mpesce/109623178869848080",
        "description": "<p>In which @timbray  makes an interesting argument, or rather, response:</p>",
        "id": 1177076,
        "pubDate": "Tue, 03 Jan 2023 03:36:02 GMT",
        "whenReceived": "Tue, 03 Jan 2023 04:03:19 GMT",
        "whenUpdated": "Tue, 03 Jan 2023 04:03:19 GMT",
        "likes": [	],
        "ctLikes": 0,
        "enclosure": {
        }

**Comment by scripting** [comment]
@josephzitt 

The time in the lower right corner of the item is a permalink. If you click it you will go to the item on the web.

![image](https://user-images.githubusercontent.com/1686843/210361606-a6c17a80-b0fa-451f-82ee-ec17635a5470.png)

**Comment by josephzitt** [comment]
Ah, OK. Could you make it blue, so it would be more recognizable as a link?

**Comment by scripting** [comment]
Joseph -- assume everything is a link. I could make a similar request that before you raise an issue, try clicking on everything in sight, or at least roll the mouse over it to see if there is a tool-tip. There is one in this case.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/1686843/210364988-1c154664-9d71-45a4-8aef-e1ee70807495.png">
