### ISSUE TITLE
News Product Error Message "undefined categories"

### ISSUE THREAD

**Issue by BrianPuckett** [scripting/feedlandSupport#168]
I am not sure if this is an error or maybe I am not using the software correctly.

I tried to create a News Product page like Dave's http://my.feedland.org/davewiner/  using my Feedland account name at http://my.feedland.org/hungrygarden/

I tagged my feed with categories that I created.  I used SETTINGS to create News Product.   When I go to http://my.feedland.org/hungrygarden/ I get an error message about undefined categories in message box.  I select OK and then url resolves with no data other than title created for product.

Thank you for your great software and any guidance.

![Category Screen](https://user-images.githubusercontent.com/97185548/213518709-5652f722-ba9c-4631-9927-e3ce88e09355.jpg)
![New Product Error undefined category](https://user-images.githubusercontent.com/97185548/213518710-97c672af-4ada-4e09-9a3a-e297e6b95e31.jpg)
![News Product Screen](https://user-images.githubusercontent.com/97185548/213518711-92cf331d-c5a7-46a2-99a8-24595484d5e9.jpg)

**Comment by BrianPuckett** [comment]
II should of paid closer attention to documentation as I see My News Product drop down selection is not active.  
![my news product menu](https://user-images.githubusercontent.com/97185548/213534548-4fe28e67-a663-41ab-a159-bf5f900c9b5a.jpg)

**Comment by scripting** [comment]
Brian this site should not have been made public yet. My mistake. Stay tuned. ;-)

**Comment by BrianPuckett** [comment]
> Brian this site should not have been made public yet. My mistake. Stay tuned. ;-)

Thank you for reply, Dave.  Incredible what you are doing!!!
