### ISSUE TITLE
Got a question about FeedLand? 

### ISSUE THREAD

**Issue by scripting** [scripting/feedlandSupport#180]
This is the place...

**Comment by oevl** [comment]
Hi Dave, I can connect to Drummer with the new email-based system, but when trying to sign-on Feedland, it says "There was an error sending the email: There is no user with that email address."

I still can read my feeds, https://feedland.org/?username=oevl 

Thanks in advance.

**Comment by scripting** [comment]
@oevl -- the two products don't share an identity system. you have to create a new account for FeedLand.

**Comment by oevl** [comment]
![Screenshot_20230319_110753_Zoho Mail.jpg](https://user-images.githubusercontent.com/174772/226188941-111abadc-7794-4908-b2ae-d9ad4bf430fb.jpg)

Because of those messages it seemed to me that that was the case.

And Feedland says my username is already taken.

**Comment by scripting** [comment]
Or don’t create a new account. You had a chance to migrate your old account,

**Comment by ReadandProgress** [comment]
Sorry for asking if it has been answered before but is there anyway to imports feeds by using a OPML file? 

Thanks in Advance!

**Comment by PG-Kelly** [comment]
@dave,  I am experiencing the same FeedLand Sign on issue that  @oevl is.  

If I  Sign on I get this error, "There was an error sending the email: There is no user with that email address."

If I Sign up I get this message, "Can't create the user "pg_kelly" because there already is a user with that name."

I did sign up for a new account.  

TY!

PG

**Comment by matthewl** [comment]
Hi Dave, I have an account on Feedland, but it now needs an email address to reset my password. I created my account when it was using Twitter as a login, but this has been dropped now. Can I be re-linked to my account on Feedland?

**Comment by scripting** [comment]
sorry -- you can't log in with twitter, so you must create another account (takes less than a minute), and subscribe to the same feeds you had on the previous account. if you tell me what the old account was (the twitter handle) i can show you how to do that.

**Comment by scripting** [comment]
It looks like you just have the default starter set of feeds.

https://feedland.org/opml?screenname=matthewlang

So there's hardly any point in restoring them. Just create a new account with your email address and when it asks if you want some starter feeds just say yes.

**Comment by scripting** [comment]
If you had more feeds, I would have suggested choosing the last option from the Subscribe sub-menu and giving it the URL of your old feeds. Here's a screen shot. 

<img width="411" alt="image" src="https://github.com/scripting/feedlandSupport/assets/1686843/61f94eb2-304f-44a2-9518-b5e7ba0b53d2">

**Comment by AboutRSS** [comment]
Hi. Thers's a tiny issue that for instance "http://aaa.com/feed" and "https://aaa.com/feed" are treated as two different RSS feeds rather than being merged into one.

Thanks for the great work by the way.

**Comment by troutcolor** [comment]
Hi Dave,
I've got quite a lot of blogs that show errors and are not being updated in FeedLand. As far as I can see they are all WordPress sites. If I go to the feed page and "Check Now" I get an error: "There was an error checking the feed: There was an error communicating with the server."

My own feed was on showing errors (it just started) so I unsubscribed and then tried to resubscribe. After quite a while I got a dialogue: "There was an error communicating with the server." I can download the feed with curl: https://johnjohnston.info/blog/feed/

Is there anything I can check?

<img width="979" alt="Screenshot 2024-05-03 at 20 07 00" src="https://github.com/scripting/feedlandSupport/assets/2952893/fe082b19-4578-4857-bda5-c4b9c17f951b">

**Comment by scripting** [comment]
@troutcolor -- let's figure out what's going on.

It looks like you're using feedland.com and not feedland.org, yes?

I looked at your feed list there. 

https://feedland.com/?username=johnjohnston

Is that the page in your screen shot?

Noted that you're viewing by Title, and when I did the same I saw what you saw. 

There *are* a lot of red feed in the list when viewed that way. 

I checked your feed in feeder, and it's able to read it. That's the same code that FeedLand uses to read feeds and it was able to read your feed. 

https://feeder.scripting.com/returnjson?feedurl=https://johnjohnston.info/blog/feed/

That's always a good way to check a feed to see where the problem might lie. 

I tried unsubscribing your feed and re-subscribing and found it took a long time, as you reported, but it did eventually come back with me subscribed. 

BTW, it would be helpful if you did not address the question to me by name. If someone else might be able to help in my experience they won't if the request is addressed to someone specifically.

**Comment by troutcolor** [comment]
Hi,

Thanks, 
Yes it was https://feedland.com/?username=johnjohnston
in the screenshot.

If I sort by When I have to scroll down to see some errors.

I tried to resub a few times, but still errored out. I could re subscribe by ticking the box on the subscription list.

I've also noticed some feeds that had an error when I reported the problem, are now ok (example https://cogdogblog.com/feed) which showed an error in my screenshot but is now fine. 

I check another feed in feeder:
https://feeder.scripting.com/returnjson?feedurl=https://adactio.com/rss/

Which looks ok, but shows error and doesn't show the latest post in Feedland

The river view 
https://feedland.com/?river=https%3A%2F%2Fadactio.com%2Frss%2F

I noticed the most recent view in the river view has [no date] as the date for the feed(?) I don't know if that is significant.

I also now see errors on my own feed although it shows the two posts I made this evening.

Check now shows an error, but 
https://feeder.scripting.com/returnjson?feedurl=https://johnjohnston.info/blog/feed/
looks fine.

FWIW my own site was down for a while yesterday for a short time, about 8 minutes according to Jetpack.

cheers

john

<img width="719" alt="Screenshot 2024-05-03 at 22 47 02" src="https://github.com/scripting/feedlandSupport/assets/2952893/6c8ecc90-3463-4adc-866f-b9676566617f">


<img width="904" alt="Screenshot 2024-05-03 at 22 50 05" src="https://github.com/scripting/feedlandSupport/assets/2952893/fd966c15-bd92-4e19-9675-ec265e363171">

**Comment by scripting** [comment]
@troutcolor -- thanks for the details/confirmation.

here's a suggestion -- try:

1. get the url of you opml subscription list from feedland.com.
2. subscribe to it as a reading list on feedland.org.
3. continue to use feedland.com.

this way we'll have a way to compare feedland-to-feedland.

it's interesting that feedland.com is (presumably) running on the same network as all the wordpresses and that might account for the problems somehow? and you'll have a great backup if things should get worse.

my biggest concern here is that you, one of our most valued users, have continued FeedLand service. 

it doesn't matter to me which server you're using.

**Comment by troutcolor** [comment]
Thanks

So I followed the suggestion, first I cleaned out my Feedland.org account, a lot of similar feeds.
"Subscribed From an OPML File URL..." 
Realised I should have subbed to a reading list so cleaned out the feeds in Feedland.org again (Note to self, read instructions 3 times)

Now "Subscribed to Reading list...", from the tools menu
Feeds get pulled across.  In the list they are green and have been updated. (I've not used reading lists before).

When I pulled them in first with "Subscribed From an OPML File URL..."  the erroring feeds did not come over. 

When I used "Subscribed to Reading list..." the erroring feeds both came across and were updated. 

When I said these were mostly WordPress blogs I think they are using WordPress but not on WordPress.com.  This is the situation of my own site, it runs on self hosted WordPress.

The screenshot shows .com on the left and .org on the right, I've sorted by name. I opened the first feed as it shows as an error but you can see it has updated on .org

As alway I appreciate the work

<img width="1920" alt="Screenshot 2024-05-04 at 18 38 55" src="https://github.com/scripting/feedlandSupport/assets/2952893/6aca9343-863d-4018-a997-d8d8ee89ac73">
