### ISSUE TITLE
No user with that email address error

### ISSUE THREAD

**Issue by galetrail** [scripting/feedlandSupport#189]
Hi,
I tried to login, but received the error above (see screenshot)
![Screenshot 2023-04-14 10 07 12 AM](https://user-images.githubusercontent.com/1824007/232098506-81173125-2f7f-4c2b-8ad2-5cf56e8ef765.png)

**Comment by galetrail** [comment]
I had an account in January-ish timeframe
matt@galetrail.org

**Comment by scripting** [comment]
We weren’t using email as identity back in January.

**Comment by galetrail** [comment]
Yes, I understand I was using my twitter account to log in, but that option does not show. FWIW my twitter account was @galetrail so I think that user name is galetrail with feedland.

**Comment by scripting** [comment]
Create a new account with your email address.

**Comment by galetrail** [comment]
So I've lost all of my RSS sources 😞
