### ISSUE TITLE
Persistent issue with sign-on and sign-up.   

### ISSUE THREAD

**Issue by PG-Kelly** [scripting/feedlandSupport#192]
At sign-on, I get an error message, "There was an error sending the email: There is no user with that email address."

At Sign-up I get the following error message, "Can't create the user "PG_Kelly" because there already is a user with that name."

I see this URL is active. https://feedland.org/?username=pg_kelly

I signed up for a new test account and had success using FeedLand.  Once I logged out  I could not sign back in.  I experience the exact same issue that is at the top of this message.

I don't have anything else to add at this time.  

I'm frustrated with FeedLand.  What am I missing?

PG

**Comment by scripting** [comment]
We switched to email identity over twitter. You missed the chance to transition. Create a new account with email address.
