### ISSUE TITLE
I can log in and pull up my my feed list but no My News

### ISSUE THREAD

**Issue by CynthiaBeauty** [scripting/feedlandSupport#201]
Hello, I seem to be unable to get My News to load, even though I can pull up my feed list. This is happening on both Safari and Chrome. Any advice?

**Comment by scripting** [comment]
@CynthiaBeauty -- there was a bug and I just fixed it. I saw the problem too.

**Comment by CynthiaBeauty** [comment]
Thank you so much, Dave. I absolutely love Feedland.
