### ISSUE TITLE
Categories Gone

### ISSUE THREAD

**Issue by troutcolor** [scripting/feedlandSupport#203]
I went into Feedland today to check on "Trouble subscribing to feeds? (Issue #202)"

Added a couple of feeds,  looked around, checked some other feeds and I don't know what, normal stuff.

Posted to My Feed.

Checked the url for the link blog, and went to My News again to test it (I've don't tried since it defaulted to feedLand.

Get an error 

_Can't get the river because there are no feeds in the "The feed for my..." category_

When I look at my categories in settings they have been replaced by 

_The feed for my FeedLand notes, link & thoughts._

So I put a couple I could remember back in and OK the dialog.

They do not stick, I've still got 

_The feed for my FeedLand notes, link & thoughts._

in the categories.

<img width="808" alt="Screenshot 2023-05-30 at 23 41 46" src="https://github.com/scripting/feedlandSupport/assets/2952893/abffc607-f183-441c-951d-6efdc2409163">

I wasn't really paying a lot of attention at the start, just doing 'normal' stuff.

Errors in the console:

500
_https://feedland.org/getriverfromcategory?screenname=johnjohnston&catname=The%20feed%20for%20my..._

and a 500 from 

https://feedland.org/updateblogsettings?jsontext=%7B%0A%20%20%20%20%22title%22%3A%20%22John%20J’s%20FeedLand%20Feed%22%2C%0A%20%20%20%20%22description%22%3A%20%22The%20feed%20for%20my%20FeedLand%20notes%2C%20link%20%26%20thoughts.%22%0A%7D&emailaddress=............

v0.5.2 

cheers
John

**Comment by scripting** [comment]
John there has been a lot of rock and rolling in that area lately. See this note. 

https://github.com/scripting/feedlandSupport/issues/199

The best approach is to just re-enter your categories. It should all start working again. 

My browser remembers them, so when I start to type, it offers to put them back the way they were.

Sorry for the disruption, but it's for a good cause, after the change it'll be a lot easier to add new prefs.

**Comment by troutcolor** [comment]
Hi Dave,
Thanks. 
the problem is that I put the categories back in and press OK but they are not saved. 

I have put then in the Home Page List and that saves. I now have tabs on my homepage that work. 

but I don't have tags in the list to choose from when trying to tag feeds. 



Cheers
John


![Screenshot 2023-05-31 at 08 08 30](https://github.com/scripting/feedlandSupport/assets/2952893/a268f1f2-4c2f-4cbb-975c-cb35db8feccf)
![Screenshot 2023-05-31 at 08 08 41](https://github.com/scripting/feedlandSupport/assets/2952893/da2f0ee8-3392-4cec-9425-faea90a6a96c)

**Comment by scripting** [comment]
@troutcolor — I’ll get on it first thing. Thanks for the report.

**Comment by scripting** [comment]
@troutcolor -- I'm now at work, this one was very easy to reproduce. These are the steps.

1. Open Settings. Click on the Feed tab. 
2. Make a minor edit to the title of the feed. Save.
3. Open Settings again. Click on the Categories tab. The feed's description has replaced the categories. 

Further, as you describe, any effort to change the categories fails to do so. 

Back in a bit...

**Comment by troutcolor** [comment]
Thanks Dave,
That has worked, thanks for the quick fix!
